# Generated by Django 3.0.5 on 2020-06-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_tag_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='writer',
            field=models.CharField(default=12, max_length=120, verbose_name='Автор книги'),
            preserve_default=False,
        ),
    ]
